# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Upload file to google drive"
  private_lane :upload_drive do |options|
    file_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]

    upload_to_google_drive(
      drive_keyfile: "fastlane/fastlanedemoGoogleDrive.json",
      service_account: true,
      folder_id: ENV['GOOGLE_DRIVE_FOLDER_ID'],
      upload_files: [''+file_path+'']
    )
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    upload_drive()
     #used to get the url of the uploaded file
    file_upload_path=lane_context[SharedValues::GDRIVE_UPLOADED_FILE_URLS][0]

    release_notes = File.read("../release-notes.md")
    release_notes= release_notes +"\nLink to apk:\n"+file_upload_path

    firebase_app_distribution(
                app: ENV['FIREBASE_APP_ID_ANDROID'],
                groups: "qa-tester",
                release_notes: release_notes,
                firebase_cli_token: ENV['FIREBASE_CI_TOKEN']
     )


    sh "echo Link to apk :" + file_upload_path
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
